// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

type Status struct {
	StatusID string `json:"statusID"`
	Name     string `json:"name"`
	Tasks    []Task `json:"tasks"`
}

type Task struct {
	TaskID string `json:"taskID"`
	Title  string `json:"title"`
	Status Status `json:"status"`
}
