// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

import (
	"github.com/naoty/tasks/backend/model"
)

type CreateTaskInput struct {
	Title string `json:"title"`
}

type CreateTaskPayload struct {
	Task model.Task `json:"task"`
}
