version: "3.4"
services:
  backend:
    build:
      context: ./backend
      target: builder
    command: ["fresh"]
    ports:
      - 1323:1323
    volumes:
      - ./backend:/tasks
  frontend:
    build: ./frontend
    command: ["npx", "nuxt"]
    depends_on:
      - backend
    environment:
      BACKEND_PORT: 1323
      CLIENT_BACKEND_HOST: localhost
      NUXT_HOST: 0.0.0.0
      SERVER_BACKEND_HOST: backend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/tasks
