version: "3"
services:
  backend:
    build: ./backend
    ports:
      - 1323:1323
    volumes:
      - ./backend:/tasks
  frontend:
    build: ./frontend
    command: ["npx", "nuxt"]
    environment:
      NUXT_HOST: 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/tasks
