SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `statuses` (
`status_id` BIGINT (20) NOT NULL AUTO_INCREMENT,
`name` VARCHAR (255) NOT NULL,
PRIMARY KEY (`status_id`)
) ENGINE = InnoDB, DEFAULT CHARACTER SET = utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
